import {useEffect,useRef,useState} from 'react'; import {AnimatePresence,motion} from 'framer-motion'; import type {DriveFile} from '../lib/drive'; import {ArrowLeftIcon,ArrowRightIcon,DownloadIcon,ShareIcon,XIcon} from './icons'; import {photoShareUrl} from '../lib/navigation';
export default function Lightbox({files,index,onClose,onNavigate,onToast}:{files:DriveFile[];index:number;onClose:()=>void;onNavigate:(i:number)=>void;onToast:(m:string)=>void}){
 const f=files[index]; const[loaded,setLoaded]=useState(false);const[downloading,setDownloading]=useState(false);const touch=useRef<number|null>(null);
 useEffect(()=>{setLoaded(false); const url=new URL(window.location.href);url.searchParams.set('photo',f.id);window.history.replaceState(window.history.state,'',url);return()=>{}},[f.id]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight'&&index<files.length-1)onNavigate(index+1);if(e.key==='ArrowLeft'&&index>0)onNavigate(index-1)};window.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',key);document.body.style.overflow=''}},[index,files.length,onClose,onNavigate]);
 const share=async()=>{const url=photoShareUrl(f.id);try{if(navigator.share)await navigator.share({title:f.name,text:'View this Faith City moment',url});else{await navigator.clipboard.writeText(url);onToast('Photo link copied')}}catch{}};
 const download=async()=>{if(downloading)return;setDownloading(true);try{const r=await fetch(`${f.viewUrl}&download=true`);if(!r.ok)throw 0;const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=f.name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch{onToast('Download failed. Please try again.')}finally{setDownloading(false)}};
 const close=()=>{const url=new URL(window.location.href);url.searchParams.delete('photo');window.history.replaceState(window.history.state,'',url);onClose()};
 return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[200] overflow-hidden bg-[#02033f]/96 text-white backdrop-blur-xl" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current===null)return;const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>55){if(d<0&&index<files.length-1)onNavigate(index+1);if(d>0&&index>0)onNavigate(index-1)}touch.current=null}}>
  <button aria-label="Close" onClick={close} className="absolute right-4 top-4 z-30 grid h-11 w-11 place-items-center rounded-full border border-white/10 bg-white/10 backdrop-blur-xl transition hover:bg-white/20 md:right-6 md:top-6"><XIcon className="h-5 w-5"/></button>
  <div className="absolute inset-0"><AnimatePresence mode="popLayout"><motion.img key={`bg-${f.id}`} initial={{opacity:0}} animate={{opacity:.2}} exit={{opacity:0}} src={f.thumb||''} className="h-full w-full scale-110 object-cover blur-3xl" alt=""/></AnimatePresence><div className="absolute inset-0 bg-[#03045e]/45"/></div>
  <div className="relative z-10 flex h-full flex-col px-3 pb-[calc(1rem+env(safe-area-inset-bottom))] pt-16 md:px-20 md:pb-6 md:pt-8">
   <div className="relative min-h-0 flex-1 overflow-hidden rounded-[1.35rem] md:rounded-[2rem]">
    <AnimatePresence initial={false} mode="popLayout"><motion.div key={f.id} initial={{opacity:0,scale:.985}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.99}} transition={{duration:.28,ease:[.22,1,.36,1]}} className="absolute inset-0 flex items-center justify-center">
     <img src={f.thumb||''} alt="" className={`absolute max-h-full max-w-full rounded-[1.2rem] object-contain transition-opacity duration-500 ${loaded?'opacity-0':'opacity-80 blur-sm'}`}/>
     <img src={f.viewUrl} alt={f.name} onLoad={()=>setLoaded(true)} className={`absolute max-h-full max-w-full rounded-[1.2rem] object-contain shadow-2xl transition-opacity duration-500 ${loaded?'opacity-100':'opacity-0'}`}/>
     {!loaded&&<div className="absolute grid place-items-center"><div className="h-11 w-11 animate-spin rounded-full border-2 border-white/20 border-t-[#48cae4]"/></div>}
    </motion.div></AnimatePresence>
   </div>
   <div className="mx-auto mt-3 flex w-full max-w-2xl items-center gap-2 rounded-[1.3rem] border border-white/10 bg-white/10 p-2 backdrop-blur-xl md:mt-4 md:p-2.5"><div className="min-w-0 flex-1 px-2"><p className="truncate text-xs font-semibold text-white/85 md:text-sm">{f.name}</p><p className="mt-0.5 text-[10px] text-[#90e0ef]">{index+1} of {files.length} · Swipe or use arrows</p></div><button onClick={download} disabled={downloading} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white text-[#03045e] transition hover:bg-[#caf0f8]"><DownloadIcon className="h-4 w-4"/></button><button onClick={share} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#00b4d8] text-white transition hover:bg-[#0096c7]"><ShareIcon className="h-4 w-4"/></button></div>
  </div>
  <button disabled={index===0} onClick={()=>onNavigate(index-1)} className="absolute left-3 top-1/2 z-30 hidden h-12 w-12 -translate-y-1/2 place-items-center rounded-full border border-white/10 bg-white/10 backdrop-blur-xl transition hover:bg-white/20 disabled:opacity-0 md:grid"><ArrowLeftIcon className="h-6 w-6"/></button><button disabled={index===files.length-1} onClick={()=>onNavigate(index+1)} className="absolute right-3 top-1/2 z-30 hidden h-12 w-12 -translate-y-1/2 place-items-center rounded-full border border-white/10 bg-white/10 backdrop-blur-xl transition hover:bg-white/20 disabled:opacity-0 md:grid"><ArrowRightIcon className="h-6 w-6"/></button>
 </motion.div>
}
